### ISSUE TITLE
Demon Brute not Dissolving Properly upon Death

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#146]
░Bug Description░ 
 
After the Brute Ragdolls, you can see the fx of the particles, but the body does not dissolve 
 
 ░Steps to Reproduce░ 
 
Kill the Brute
 
 ░Screenshot░ 
 
![Media](https://drive.google.com/u/0/uc?id=undefined&export=download)
 
-Luke

**Comment by nbaggett** [comment]
Fixed ( dissolves will be changed to use one material in the future so this doesn't happen )
