### ISSUE TITLE
Locked Crafting Recipe Tooltip

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#147]
⁠On crafting item tool tip, lets show where a recipe can be found. is it bought from a specific vendor, found from specific drop, created, etc. Lets just add an additional description type called recipehint on the scriptable object that would say things like "The blacksmith could probably teach me how to make this or I bet I could figure out how to make this with enough XP"

for now set the default to "This recipe can be learned from a schematic".

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/2634d677-09cd-4c05-bed7-78752f4b0c89)

**Comment by nbaggett** [comment]
Added as a property to scriptable items, now shows hint in tooltip for locked recipes.
