### ISSUE TITLE
Crafting item tooltip should show gold sale price

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#148]
Crafting item tooltip should show gold sale price (make sure we use the same formula that we calculate vendor price) -- ask ty

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/a1785d20-c4e1-4482-b086-129a9a1f8f24)

**Comment by nbaggett** [comment]
implmented in 631ad1d
