### ISSUE TITLE
Crafting screen locked items should apply greyscale material to tooltip

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#149]
instead of alpha, this material should get applied to the tooltip when hovering over a locked recipe, causing the icon to be greyscaled.

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/2bf6b300-f57d-4e28-8ea9-d9d7706c38f6)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/d22165ec-5f44-45a4-9049-99ffbe862968)

**Comment by nbaggett** [comment]
Done in 631ad1d6e5cb80e972827081df8aae6b14e5efcb
