### ISSUE TITLE
Water Barrel, Shelves, Anvil, and Fireplace cannot be placed

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#151]
Water Barrel, Shelves, Anvil, Wooden Craft, Fireplace, Rug cannot be deployed. There may be others. please check every spawnable deployable and verify that they function and that they are deployable

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/4ce2a990-622c-4120-8730-88014a708789)

**Comment by nbaggett** [comment]
Done, will set these up to be pick up-able when I implement the new hold interaction functionality
