### ISSUE TITLE
shift clicking a stack when your inventory is full can cause issues:

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#154]
lets just disabled shiftclick/middle mouse auto split if your inventory doesnt have room to move the split anywhere
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/47a72c6e-cb4a-4c04-a6b8-93463522ed65)

**Comment by tykennington** [comment]
This pointed me toward a bigger issue of it breaking when dragging over other other items, whether there's room elsewhere or not. Fixed in commit 7705be3 by just rolling back the change when you let go.
