### ISSUE TITLE
Item Textual feedback shows +xxx even when losing an item. it should show -xxx

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#155]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/10b76dc4-5a7a-4c0d-84b9-63b4334cfe28)

**Comment by jkhan007** [comment]
Bug Fixed! 

Screenshot
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/ec00067b-e4d2-432a-8016-ca8101607b9a)
