### ISSUE TITLE
Add new recycler sprite panel

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#158]
have the following slide in for the recycle ui. When this UI is active, we need to hide the crafting panel UI:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/1e3c8ff2-1045-4fa0-870f-100ebaf11c7d)

**Comment by westonleavitt** [comment]
it and all other panels are located here:
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/2b26b194-bad0-49f8-8115-199247998395)

**Comment by tykennington** [comment]
commit d98ddc2
