### ISSUE TITLE
Storage Vendor UI Sprites

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#159]
Have large and small storage use the following new sprite panels located here:
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/ae976978-94cd-495f-9ebe-f1a5dfa9519d)

the wooden storage crate should have 36 slots and the large storage should have 72:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/e0b44b0a-f1ad-424a-a453-7ea03aed8b60)

**Comment by tykennington** [comment]
commit d98ddc2
