### ISSUE TITLE
Vendor Types Sprites

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#160]
adjust the vendor panel to show the VendorAndRepair when talking to a vendor that has repairing as an option
:
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/4484c252-44a8-4c80-a892-cc3e61a63ccc)

use the same layer styles for font that is currently in the crafting panel:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/fac36fb8-557e-4af5-acdd-09caff574b69)

**Comment by tykennington** [comment]
commit d98ddc2
