### ISSUE TITLE
Craftable Items need crafting preview setup on their scriptable item

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#162]
Our crafting panel supports an in UI prefab preview of the craftable item:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/a8e106dc-0c4d-4374-8f2d-9bab7efd1b6d)

this prefab is set on the scriptable item for the individual craftable recipes:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/b1483042-2c6d-4262-bae2-a0fd00b5ff88)

the system attempts to find a prefab on "Custom Preview Prefab" but if that is null can use the held item prefab as well.

The task for this is to click through all the craftable items and verify that each have a unique item setup that displays the crafted item. If it doesnt have an item setup, create a duplicate of the held prefab and set it to the custom preview. 

you can also use the Local Position, Local Rotation, and Local Scale to make adjustments to guarantee the preview fits the panel in play mode appropriately

**Comment by jkhan007** [comment]
Completed except for Gloves prefab
Demo Video
https://streamable.com/5nm6yi
