### ISSUE TITLE
Equipment Panel Sizing for Grids

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#163]
slots are slightly off on this panel un the ui, causing the icons to be slightly off. they just need to be hand place back into the appropriate position:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/e4d7f7a7-5efb-45ae-8190-51160dff5b86)

**Comment by jkhan007** [comment]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/bc2516f6-8f95-4ee3-b03c-bc3252044fc7)
Completed!
