### ISSUE TITLE
if you mousing over a locked crafting item and then move to an item, the sprite for the tooltip item will display as transparent because not getting reset

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#167]
if you mousing over a locked crafting item and then move to an item, the sprite for the tooltip item will display as transparent because not getting reset
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/750b88b0-bed0-4206-97c4-f360b5ead62e)

**Comment by jkhan007** [comment]
https://streamable.com/ariopx
