### ISSUE TITLE
Always default the crafting to show the first tab

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#170]
set crafting to auto default show the first ("Building" tab) instead of nothing on first load:

wrong:
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/67d0b9f9-78ab-452a-b9a9-c8c2dc1511f5)

right:
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/aa8cf920-3137-4dea-82cb-91477ec1903f)

**Comment by westonleavitt** [comment]
you will need to adjust this component:
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/0cc52be3-5d7a-41cc-8d94-36a7c18dcd59)

**Comment by jkhan007** [comment]
![Uploading image.png…]()
