### ISSUE TITLE
Tie in Latency and FrameRate on Alt View Header

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#171]
Adjust the static text fields in uicontroller to update in real time based off the current ping/frame rate from relevant components.

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/e1559a1d-393a-4c6e-823d-f7c424c760ea)

**Comment by jkhan007** [comment]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/db80f676-4b14-4472-bb26-20c60b27f79b)
Added the reference code of the ping along with FPS
