### ISSUE TITLE
hide any instances of tooltip information on locked crafting items

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#174]
hide any instances of tooltip information on locked crafting items

stuff like this should be gone:
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/1c7bccdb-4540-4a28-8693-b67fdd3c7272)

**Comment by jkhan007** [comment]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/cfade7ab-9623-467f-b3ac-c1c8bc7ce2d8)
