### ISSUE TITLE
Add movement lock / checks

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#175]
checks need to be added so that you cant move around while typing in 
1. search bar for crew, 
2. in crew name field, 
3. in search bar for crafting.

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/82f530d5-667f-405f-888f-873ad1fee717)

**Comment by tykennington** [comment]
Fixed in commit 1a1736a
