### ISSUE TITLE
Torch crafting preview looks funky because of particle system

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#178]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/e6788c11-1e1c-437f-a654-d97501dccb8a)

fix by creating a duplicate for the crafting preview instead of using the held version. Then remove the particle system on the crafting preview

**Comment by jkhan007** [comment]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/f8b39ea2-74e9-4f96-85f4-28f22ec0f5dc)
