### ISSUE TITLE
The tooltips for consumable have an issues where items show hunger/hydration instead of bonus health/energy

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#181]
Lets diagnose the issue then fix any scriptable items where its the case

Correct showing (some items are proper):
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/f8221062-322c-4e54-a14c-36dba32a302b)

Incorrect showing (some items):
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/f2b94aba-f4d1-42c0-9164-763a75693436)

**Comment by tykennington** [comment]
Fixed in commit 2d63b4d. I looked through all the other foods and consumables, and it was only the Meat Pie that was like this.
