### ISSUE TITLE
Settings menu has no sound setup. Use the same sounds that are on

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#184]
Do a complete pass on the settings menu and make sure each action has sound. Each input object -- Checkbox, dropdown, and slider, should play this sound on hover:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/de073372-6a60-4df6-8caa-78186f55be87)

and this sound on click:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/15e92561-c33f-4078-9171-04647a9969c8)

**Comment by jkhan007** [comment]
Added All the sfx sounds in the setting menu checkboxes, dropdowns and sliders
