### ISSUE TITLE
Stacking Crafted Items Error

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#188]
### What happened?

If you craft 2 weapons (or any item), it stacks them and lets you equip the stacked items, but won't let you combine them with more of that item. And it lets you equip a stacked item. Shows that you are holding 2 knives, etc.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by tykennington** [comment]
Fixed. Commit b74ac1b
