### ISSUE TITLE
Dropping Items while Crafting

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#189]
### What happened?

When having the crafting menu popped up, and you drop the item needed to craft out of your inventory, it 

1. doesn't update that resource amount, and
2. plays the wrong audio when trying to craft

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by tykennington** [comment]
Fixed. Commit b74ac1b
