### ISSUE TITLE
Jumping from water to land

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/TheOccultBugTracker#19]
[https://streamable.com/08ih53](url)
When trying to leave water by jumping onto land a lot of the time it will just cancel your upward momentum and force you down. This happens on land sometimes too but less frequently and I haven't been able to replicate it. Other times it works fine, as you can see in the video. A few days ago, when having this problem, I did see in the console a message about 'tick decay' or something similar every time it would deny my jumping. But it hasn't been showing up lately. So, it might not be related.
Currently if you hold forward while jumping from the water trying to get up (as I assume most players would in game) it happens almost every time, but if you jump up then push forward it _usually_ doesn't happen.

**Comment by westonleavitt** [comment]
Heavily tweaked to improve this performance. Should be much smoother
