### ISSUE TITLE
Upgrading Frames Issue

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#194]
### What happened?

Upgrading frames to wood doesn't take resources (this might be false negative. it doesnt take wood out of the stack in the action bar, it takes it out of any stack in the inventory). Maybe just double check that. Thanks! 

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by westonleavitt** [comment]
closing this. it does remove wood, it just currently pulls wood from other stacks in your inventory first. (this will get fixed when #220 is complete)
