### ISSUE TITLE
Clients can't see equipped items, host sees their item as equipped for everyone. 

### ISSUE THREAD

**Issue by nbaggett** [westonleavitt/TheOccultBugTracker#20]
Steps  to replicate:
1. Have a client connect **_after_** the host has equipped an item
2. The host will see their equipped item in the clients hand's and clients will not see any item equipped. (ignore the invisble meshes, that's a UMA issue)

Host view (Bow equipped, bow also equipped for client):
![image](https://user-images.githubusercontent.com/43483627/207731103-1979da52-1bd2-4ce6-acb4-9ebb6b95fc8a.png)

Client view (host has bow equipped but this is not visible):
![image](https://user-images.githubusercontent.com/43483627/207731185-ef765914-b690-4c54-872c-c6b592075767.png)

**Comment by westonleavitt** [comment]
rewrote this to be fully state/listener based. should be crispy now
