### ISSUE TITLE
Supply Barrel Not Showing

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#200]
### What happened?

Supply Barrel doesn't show when equipped

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by nbaggett** [comment]
Supply barrel still WIP, will function when the deployable is finished.

**Comment by nbaggett** [comment]
Going to close this for now since it isn't a bug
