### ISSUE TITLE
Sleeping Bag Residue

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#202]
### What happened?

When picking up Sleeping Bag, it leaves grey highlight, which then breaks placing anything down after.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by nbaggett** [comment]
Fixed a different issue with safe zones not updating in a specific case after picking up the bag, but this was likely a player data clear related error.
