### ISSUE TITLE
Smelted Ore can't be picked up "Inventory Full" Error

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#208]
### What happened?

Smelted Ore can't be picked up "Inventory Full" Error

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by nbaggett** [comment]
Cannot replicate, likely due to local player data not cleared. Did fix an issue with the furnace not showing the correct notification though.
