### ISSUE TITLE
Geode Station uses all geodes at once

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#209]
### What happened?

Using Geode station uses all of your geodes in your inventory. (Change to just one)

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by nbaggett** [comment]
I had it mass consume all valid items as a QOL thing but I've changed draggable machines (geode stations, etc...) to use only one of the resource.
