### ISSUE TITLE
Fix Shaders to blend seamlessly underwater

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#21]

**Comment by mckayrules** [comment]
https://streamable.com/awhtdv
I found a workaround to the seamless underwater materials. The volume still functions the same and has the normal surface water effects without it going down the sides or bottom of the volume and being all weird.
You just put a plane on the surface then remove its collider (which I forgot to do in the video) and give it the water material you want. Then turn off (or remove) the mesh renderer on the volume.
