### ISSUE TITLE
Storage Crate Pickup Bug

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#211]
### What happened?

After placing storage crates, and holding click to pick up, they just drop on the floor, and don't go into your inventory 

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by westonleavitt** [comment]
Can't seem to duplicate. likely a localdata issue. re add if you experience again with more details (i.e. are you receiving error in console or global chat saying inventory is full?)
