### ISSUE TITLE
Stone Wall Shadow Bug

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#218]
### What happened?

Sun doesn't leave shadows on stone walls.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by westonleavitt** [comment]
likely related to test volume or extra directional light. this doesnt happen in open world with proper setup:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/d4d0a046-4c68-4764-9427-315044e51b35)
