### ISSUE TITLE
Add Scrollbars to Crew

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#219]
Adjust mask/scrollbar setup for each of the tabs (Your Crew, Friends List, Invites) in the crew tab. You can access the crew tab by clicking on "Crew" in the top bar. Just use a grey rectangle for the scrollbar

this is what it looks like
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/44e8d7e9-11da-4776-b260-0f4a5b132f42)

here is what it needs to look like (with the functioning scrollbar)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/a568fe10-9ba4-4b74-92cd-f45d389febc7)

**Comment by jkhan007** [comment]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/1fbce749-198a-42c1-a87c-85901d30adc0)
