### ISSUE TITLE
item resource usage should take from active slot, other item slots, then the player inventory

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#220]
Spending resources, i.e. upgrading building walls, using arrows, consumables, etc, currently searches the player inventory and uses any instances of the items there first. This causes disconnect in many places because resources dont seem to remove or deployables are still in the action bar after getting placed.

Lets check and use what is in the current action slot first. Then check the other non active action slots. THEN check the inventory.

**Comment by tykennington** [comment]
commit 5795526
