### ISSUE TITLE
Consumable Tooltip Coroutine Tick

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#221]
currently our tooltips when scrolling over consumed food show the remaining time left:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/be54aa4b-2dd4-4ac6-9117-6204edd8db3c)

this indicates how much time is left until the buff will be lost. I want to adjust the tooltip to tick each second, showing the duration changing. You will need to start a coroutine when you mouseover and stop the coroutine when you pointer exit.

the format should also be: 4m 20s (note the space)

**Comment by jkhan007** [comment]
https://streamable.com/idl0ji
