### ISSUE TITLE
Deployables should not be stackable

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#222]
deployables should not be stackable, do we have an easy way to remedy this?

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/dadd7df6-830d-47e7-98e3-ae673fb9a571)

**Comment by nbaggett** [comment]
Made a new building condition for placing parts that considers objects under the part. Uses a surface identifier component on the root object so we can place boxes on shelves, but not boxes on boxes. Sleeping bags on terrain and floor pieces and nowhere else, etc...
