### ISSUE TITLE
No Sound or Particle Fx when Hitting Built Structures

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#224]
### What happened?

No Sound Effects when hitting upgraded wood or stone structures (does work for placed doors) -- also building parts just dont show up with aimcanvas in general

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by nbaggett** [comment]
I changed the FPCombat to ignore collision with interaction tags so it ignores the colliders for the building part interactable components. If this is an issue we will need to probably make a layer ignore for interacables.
