### ISSUE TITLE
Placing Deployables Duplicate Bug

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#226]
### What happened?

When you have 2 of the same deployable (sleeping bag, trap, etc) in your inventory, and you equip and place one, it automatically pulls one of the other deployables in it's place on the inventory, but does not show the deployable in the in-game screen space. 

You have to unequip that second deployable and re-equip it for it to work.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by westonleavitt** [comment]
This is a duplicate that has already been assigned to nick
