### ISSUE TITLE
Deploying one item will consume two

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#228]
having two of the same item in two seperate action bars and then deploying one:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/0608696c-7453-4b3c-99c0-9073f755d54e)

will consume both the items but only place one:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/62d95ab7-60dc-43f7-b93a-d8c3648c07ed)

**Comment by tykennington** [comment]
commit 5795526
