### ISSUE TITLE
Fall damage sound and screen shake

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#236]
adjust the scripts here:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/7df92201-5413-40ff-98b4-c0a06e9b9729)
 
in PlayerMovement.cs to play a local sound when you fall. make it some sort of impact sound, something that would seem natural for a sound that would play when you fall from a far distance.

also call this method:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/f53a54c2-c177-40f0-b3f3-1f19d34d916e)

CameraShaker.Instance.MediumShake() so that when you fall the camera gets a shake as well.

**Comment by jkhan007** [comment]
Added Fall Jump, Damage sounds and calling screen shake in the code!
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/634f9314-7440-4fb2-881c-477fd31f7d2b)
