### ISSUE TITLE
Falling VFX Volume

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#237]
use the falling scripts in PlayerMovement in combination with the GlobalVolumeController to turn on a falling volume when the player is falling. you will have to 1. create a new type of volume detection inside of globalvolumecontroller, then 2. when falling in playermovement, do GlobalVolumeController.instance.EnableVolume( using the new volume type), then 3. disable the volume when done. 

As far as the actual volume settings go, just turn the chromatic aberration up all the way (i'm sure we will add other tweaks as well)

**Comment by jkhan007** [comment]
Falling VFX ADDED and  enable/disable volume when the player hits the ground from certain height 

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/d04d82d4-7567-44c8-a02c-6b17a9a00e7b)
