### ISSUE TITLE
Displaced players

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/TheOccultBugTracker#242]
### What happened?

Luke was building in the cemetery walls, but he appeared pretty far away from there for me. It looked like he was walking around and just in the sky. But I think that was just because of the elevation difference between where he was actually and where he appeared. The z-height seemed to be the same or similar. It was the x and/or y that was off.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Don't know. Possibly the same reason we couldn't see people sometimes. Maybe they were just shifted off to the side pretty far so it seemed like they were invisible to us.

### Screen Recording or Screenshot
![8d34ca91-0f12-49f9-8c8b-c078fca66880](https://github.com/westonleavitt/TheOccultBugTracker/assets/109044284/00b0e3cc-937c-4f39-bfd2-d25eaf4edb74)

**Comment by westonleavitt** [comment]
fixed
