### ISSUE TITLE
Palm Tree Highlight Jank

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#248]
### Contact Details

.

### What happened?

The highlight for these palm trees are janky.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Look at Palm Tree.

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/100382919/24fd544a-e093-464f-9817-4793a3d162bd)

**Comment by westonleavitt** [comment]
removed from game
