### ISSUE TITLE
Loading in Server "Last Played: Never" &

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#257]
### Feedback

I just noticed that when getting into the game, it doesn't register that you've ever been in the server at shows "Last Played: Never"

**Comment by jkhan007** [comment]
Fixed! 

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/148d62f7-dbeb-4d56-a75f-8d462c83b244)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/11eb7d1c-8349-48de-8659-9ac643c0c530)
