### ISSUE TITLE
Resolution changes within "Settings" doesn't work

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#264]
### Feedback

Resolution changes within game "Settings" isn't working

### (Optional) Screen Recording or Screenshot

.

**Comment by westonleavitt** [comment]
@tykennington for the time being can we setup just two options 1920 x 1080 and 2560 x 1440

**Comment by tykennington** [comment]
Should be fixed in commit 02b7a43, but it has no effect in the Editor. We can verify this in the next build.

**Comment by tykennington** [comment]
Verified in steam build. It defaults to the screen resolution, and if that isn't listed, the first option on the list (currently 1920x1080). Changing from the dropdown does take effect immediately.
