### ISSUE TITLE
When you eat food it removes the whole stack instead of just one

### ISSUE THREAD

**Issue by nbaggett** [westonleavitt/TheOccultBugTracker#267]
I think this is related to my issue with throwing objects removing the whole stack as well. When I call `PlayerDataCollection.instance.RemoveItem(uniqueId, ItemSlotType.Weapon, itemPos, 1);` it still removes the entire stack instead of just one. I put a log in the removal code and it looks like the item quantity in the inventory is not tracking properly (just 1 for any stack size)

Issue was found when doing host with test wrapper.

**Comment by tykennington** [comment]
commit acdcfed

Adding that 1 to RemoveItem() worked in this case, so I'm not sure what's happening with throwables
