### ISSUE TITLE
Explosive barrels not always deploying even when green

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#269]
### What happened?

The placement marker turns green, but when I left click to place an explosive barrel it just unequips it. I tried with a barrel in different inventory slots with the same result. (the barrel that is placed is leftover from a previous test).

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

https://streamable.com/gzfjpj

**Comment by westonleavitt** [comment]
I watched this fail on the server. the server build check fail but the client check passes

**Comment by nbaggett** [comment]
This was related to the server desync with the player position I think, closing for now but if we still keep getting building issues like this one after the desync fix I will re-open
