### ISSUE TITLE
Teak tree LOD distance or triangle adjustment

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#289]
### Feedback

The new teak trees have some funky looking LODs that, in my opinion, maybe need their distance pushed back or triangles added to LOD 2.

### (Optional) Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/dd024a7f-7277-4146-80e9-95e015d2d264)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/b09f36c5-7389-450d-ae0a-00b8c5d84e55)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/01f9e999-74eb-43dd-8ffe-7c68c707f166)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/a48b7c6b-b30b-45ef-8f92-77715865cf36)

**Comment by mckayrules** [comment]
Should be better now, let me know if there is something I missed.
