### ISSUE TITLE
Move chat inside when alt view is open

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#290]
add a part to the state based ui for the chat so that when the alt view opens, the chat slides over and is still visible -- i.e.

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/bd8eecf5-31be-4624-85a4-f4d874c0751b)

**Comment by jkhan007** [comment]
![Uploading image.png…]()
