### ISSUE TITLE
Change interact on buildable doors to "close" or "shut"

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#291]
### Feedback

When a door you've built is open, the interact currently says "open" again. Should probably say "close" or "shut" instead.

### (Optional) Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/e2100cb1-b1d6-4ee7-b261-b9a8d357b721)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/ef3ffd40-c611-4733-a67f-83223775e988)

**Comment by nbaggett** [comment]
implemented in latest
