### ISSUE TITLE
Make throwing objects action repeatable if stacked

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#292]
### Feedback

Just a potential QOL change, but it's annoying when you have a big stack of something like rocks that you're throwing, and between each rock throw you have to re right click and hold before throwing with left click. Would be nice if you had a stack of a throwable object if it just had an action cooldown like a weapon, so you could keep right click held and repeatedly throw them as fast as the cooldown allows. Not spammable like it was at one point, just repeatable without having to reclick/hold everything.

### (Optional) Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/a13098b0-f7eb-4796-a071-90a606fa3877)

**Comment by westonleavitt** [comment]
ultimate throwing fixed now
