### ISSUE TITLE
lets adjust bushes to use a auto mechanic similar to chest so you dont have to sit and hold the button

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#294]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/1dd0c1d3-c821-4057-b3c3-389b197b0ba7)

**Comment by tykennington** [comment]
commit 9c8a5bb

Added this feature to the Shrine script, so we could do something similar with other non-storage interactables if we want
