### ISSUE TITLE
Couldn't complete the last step of the tutorial

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/TheOccultBugTracker#314]
### What happened?

I got to the last step and tried throwing stuff as it said but nothing would progress the final step. I tried rocks, bones, an axe and bronze key.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Get to the final step of the tutorial, throw and it doesn't complete.

**Comment by nbaggett** [comment]
This was an issue with desyncing the tasks where it was completed before the animation was finished. now will snap the text if the last task finishes
