### ISSUE TITLE
Scroll to cycle through hot bar items

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/TheOccultBugTracker#315]
### What's your idea?

It would be nice if you could use the scroll wheel to cycle through the items on the hotbar. Though some cases probably should block it, like during building or placing deployables. Maybe it's a shift + scroll wheel thing.

**Comment by tykennington** [comment]
commits 0f6b446 and f2e0927

Right now it goes up or down 1 slot per scroll, counting a scroll as all input before 150 milliseconds of dead time
