### ISSUE TITLE
No "inventory is full" message if loot table is open

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#319]
### What happened?

If your inventory is full and you're interacting with a loot table, you don't get a message that tells you your inventory is full when you try to loot additional items.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

-Have a full inventory
-Interact with an abandoned cart
-Right click items to loot

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/7d66f2bc-1695-4fb8-bdc4-4d4c57a1520f)

**Comment by westonleavitt** [comment]
This should be fixed now that chat slides over with the UI
