### ISSUE TITLE
Tutorial progress doesn't save on server exit/rejoin

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#322]
### What happened?

After completing a number of steps in the tutorial, or the entire thing, when you exit/reenter the server the prompt appears that "you're a new player, here's the tutorial step 1, etc" 

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

**Comment by nbaggett** [comment]
should be fixed in latest, I'm unable to replicate losing progress but I was able to replicate the pretutorial showing every time
