### ISSUE TITLE
Ensure all resources are available in build to complete tutorial

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#323]
### What happened?

Through either looting, harvesting or crafting we need to have all the resources available to 100% complete the tutorial without using dev console cheat codes. Probably just a matter of modifying the loot tables of what's currently available on the build.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

**Comment by tykennington** [comment]
Bushes now give +5 cloth each
