### ISSUE TITLE
books textures are broken

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#328]
We broke alot of books by not using duplicate textures/materials. Lets go through all the books in the console and test their held and world space drop verison. any that are broken we need to fix

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/c5833f36-4be1-4dca-a258-360a5c18de72)

**Comment by lukewoodruff** [comment]
Fixed on all recipe books. All other books look good.
