### ISSUE TITLE
Can grow trees beneath houses

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/TheOccultBugTracker#342]
### What happened?

Trees can be planted below houses, and then grow upward into the house

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

1. Build a house that's off the ground.
2. Deploy saplings on the ground beneath the house.
3. Wait for saplings to grow
4. You now have trees in your house

### Screen Recording or Screenshot

![treehouse](https://github.com/westonleavitt/TheOccultBugTracker/assets/105509370/3f2ac7ce-6349-4529-88c1-dfd0f7b539a8)

**Comment by westonleavitt** [comment]
Can we add a raycast upward check condition to make sure these can’t be placed beneath anything with a collider @nbaggett

**Comment by nbaggett** [comment]
fixed, new condition added for checking in a direction
