### ISSUE TITLE
Leaving Water Fall Damage

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/TheOccultBugTracker#35]
When you leave a water volume and touch the ground it will compare where you last were on solid ground to where you are now and register it as a fall from that height. At least I think that's what's happening. It does scale with distance. I found this on accident by leaving the water volume pretty deep down and it insta-killed me to around -700hp. This little test video is a much shorter drop but shows the same effect.

[https://streamable.com/b4ff06](url)

**Comment by westonleavitt** [comment]
fixed
