### ISSUE TITLE
Repeating Issue that breaks missile manager/physics on the server

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#354]
Likely causing rigidbodies to stop receiving network updates:
 
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/2ee7cb71-88ac-4df9-b0a3-e5cf289d3bb9)

this causes signficiant issues with pretty much all other network operations

**Comment by nbaggett** [comment]
fixed
