### ISSUE TITLE
Stair placement Issues

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#361]
### Contact Details

Luke

### What happened?

Not able to place stairs on certain pieces of ground. Maybe due to the unevenness of the ground? It shows green, but will not place

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Build foundation on hill
try and build stairs leading off of it

### Screen Recording or Screenshot

https://github.com/westonleavitt/TheOccultBugTracker/assets/100382919/c3c79ca2-97b1-4fb1-a243-691e2bfde10c

**Comment by westonleavitt** [comment]
Duplicate of #346
