### ISSUE TITLE
Styling issue where chat can get cut just when it overflow the bounding box

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#362]
I dont have a screenshot in game, but chats can do the same things the input box here does with the hanging gs:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/2478e3f2-2eae-4f7a-80a9-75228f4a0eeb)

I think its just a setting on the textmeshpro to allow overflow text

**Comment by tykennington** [comment]
commit 9057cba

It was the parent rect that was too small and was masking it (because it used to be a scroll view)
