### ISSUE TITLE
Crafting categories not showing:

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#372]
Crafting categories not showing:

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/d21fa5fb-f885-469e-83ec-7b6d91fbe16c)

**Comment by jkhan007** [comment]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/39084382/d52d9d96-1d97-4265-be85-64dd5e889fca)
Fixed & pushed the updated UIController Prefab
