### ISSUE TITLE
Spells collide with self almost always

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#375]
Spells/Projectiles almost always just hit the collide with the player. Can we do some checks to just 100% guarantee they cant hit themself with a spell

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99469587/a96e81c4-e1a8-4e6d-b4b9-4b4fe9ca9207)

**Comment by nbaggett** [comment]
I know what this is, I have spells ignore collision with the player who cast it's capsule but not the player limb colliders.
