### ISSUE TITLE
Multiple Colliders In Psychosis Volumes

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#38]
When you initially enter one of the colliders, psychosis starts ticking on the player, but when you leave the collider you're in and enter a new one (even overlapping colliders) the psychosis stops ticking.

![image](https://user-images.githubusercontent.com/99694322/210908027-409011b4-e446-487e-b629-d7020706f934.png)

Another consideration is having multiple adjacent psychosis volumes with varying degrees of the effect. For example, in this monument I want everything above ground to have belong to one psychosis volume with lesser effect, and when you're below ground in the dungeon another psychosis volume with greater effect. 

![image](https://user-images.githubusercontent.com/99694322/210908096-1522edf2-ffad-4697-8f40-0972f368c96a.png)

**Comment by nbaggett** [comment]
fixed, will be in next push with spawner feature changes
