### ISSUE TITLE
Bed placement issue

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#386]
### What happened?

Bed flashes between red and green rapidly when trying to place it. A few times when it would go through, the bed would just disappear. Ultimately I was able to randomly place it between flashes, but not reliably.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

https://streamable.com/ka0kue

**Comment by nbaggett** [comment]
fixed
