### ISSUE TITLE
Resource values not tracking correctly when dropping from inventory - crafting queue freezes

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#395]
### What happened?

I dropped lumber from my inventory then hovered over an item to craft (building hammer) and it still shows that I have the resources that I dropped. It lets you click craft, the item goes into the crafting queue, but then it freezes when the timer runs out and the icon remains and it doesn't actually craft the item.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

1. Harvest lumber (enough to craft the building hammer)
2. Drop from inventory
3. Try to craft the building hammer

### Screen Recording or Screenshot

https://streamable.com/1pyu1q

**Comment by tykennington** [comment]
commit 8e2795e

Fixed by making the crafting UI update if it's open and the inventory receives an update. Also made sure the item doesn't make it to the queue UI until it gets the okay from the server
