### ISSUE TITLE
Food consumed stays even after death

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#396]
### Contact Details

Luke

### What happened?

After you die, it saves and displays what you previously had eaten / drunk when you respawn. It should clear those three slots.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

.

**Comment by tykennington** [comment]
commit 8ad8119

Now it resets you with just "leftovers" like when you first join the server
