### ISSUE TITLE
Floating harvestables

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#399]
### What happened?

Ran into a large area with floating trees, stone, etc. Assuming these objects are still at the elevation of the old terrain maybe?

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/a3265bbc-8ee0-4237-b719-14a292b6554f)

**Comment by westonleavitt** [comment]
this was human error. I added checks in prebuild to make sure these all get reset
