### ISSUE TITLE
Building bug seemingly tied to worldspace objects on ground

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#401]
### What happened?

Building part is red when trying to place on top of a worldspace item, then after picking up and removing the item, the building part turns green and snaps in place but doesn't actually let you place it.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

https://streamable.com/hsp9hv

**Comment by nbaggett** [comment]
Loot is now all on a different layer so it doesn't interfere with building (or raycasting placement of parts for that matter).
