### ISSUE TITLE
Resource in action bar should pull from all of that same resource in inventory

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#402]
### What's your idea?

Currently when you're using a resource to upgrade building parts the quantity is based on the single stack you equip. This makes it really annoying when you're trying to upgrade lots of things at the same time since you have to repeatedly add a new stack to your action bar. Would be a good QOL change to make it so when you add a resource to your action bar it shows the total number of that resource in your inventory and pulls from your entire inventory instead of a single stack. 

### (Optional) Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/37ec3ab5-8311-46cf-8fad-a351ec038433)

**Comment by nbaggett** [comment]
no longer an issue, new building hammer solves this problem
