### ISSUE TITLE
Trees respawn inside already built bases

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#404]
### What happened?

Built a base and after some time trees started spawning inside of the structure

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/1213dcd0-453f-4e25-9965-20464b7a4824)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/e9541717-f193-4e7a-a90a-e179cbb0908e)

**Comment by westonleavitt** [comment]
this is blocked now
