### ISSUE TITLE
Unable to place some deployables on the terrain

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#405]
### What happened?

At least the planter box and mailbox are unable to be placed on the terrain with no obvious obstructions

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/49e5aef6-8bab-43f2-aa36-8a26cf2bc165)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/dbf16cd2-5ba9-4f01-85fa-b1008918b040)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/3f26eb92-16a6-4c84-a81c-13becee774a4)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/192764d4-626c-488b-96f7-e64e24ff0744)

**Comment by westonleavitt** [comment]
fixed with terrain
