### ISSUE TITLE
Sign painting nearly impossible to see

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#408]
### What happened?

After painting a sign and saving it you can't see what you've painted

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/2b7251c9-9a4d-4913-b29b-5c1ddf338aa9)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/b7d725da-a0f6-4977-b35f-2a70b906b044)

**Comment by westonleavitt** [comment]
removed black emission, removed 100% metallic
