### ISSUE TITLE
Remove item on interaction doesn't fully remove item

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#410]
### What happened?

After interacting with a locked door, the key is removed from your action bar but stays in your hand.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/087a3f11-d1eb-4c4e-9346-36c7cd5dcb04)
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/2dff5559-aca2-4218-a3f3-674d6d122bb6)

**Comment by tykennington** [comment]
Fixed in commits 0faf4d7 and e4b590c

Moved the item check server-side
