### ISSUE TITLE
Wrong info on inventory count

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/TheOccultBugTracker#419]
### What happened?

It's saying that I have over 1k wood but I only have 160. When I get new wood it adds to the total but doesn't go down when using the wood. At least that's what it seems to be doing.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

1. Harvest wood
2. Use wood
3. Wood doesn't disappear

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/109044284/37fb41f1-3a12-4ae0-9fad-4edc59da6927)

**Comment by tykennington** [comment]
commit c3973a2
