### ISSUE TITLE
Chest remain open even if you close alt view

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#42]
If you tap alt after having the chest ui open the chest UI remains while the alt view closes. Lets adjust it to automatically close any open chests if you tap alt.
![image](https://user-images.githubusercontent.com/99469587/211225828-2ddcd352-1007-41b1-8de2-a10d51ce0c34.png)

**Comment by tykennington** [comment]
Fixed. Solution cancels all cancellable interactions with alt, including dialogue, which seems like what we'd want anyway imo
