### ISSUE TITLE
Bed deployable shows as Sleeping Bag on map with partial/incomplete tooltip description

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#434]
### What happened?

Placed a bed and opened the map to see the location, noticed it shows that it's a sleeping bag and the description tag is cut off

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/4786cd9c-37e4-4295-bf47-929d6e310e76)

**Comment by tykennington** [comment]
commits 1b2f8c9 and 116a672
