### ISSUE TITLE
Goblin AI aggros enemies

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#45]
Hard to tell maybe because the video quality is crappy, but at the end you can tell it aggros the rats from the ground when you enter combat with the goblins - the rat spawn point and way points are all on the ground.

https://streamable.com/06o5hq

**Comment by nbaggett** [comment]
I'm going to leave this open for now, but I'm having a hard time recreating this issue in a different scene. I think it might go away when we build, but I'll keep an eye on it.

**Comment by nbaggett** [comment]
@psyqotic is this still happenning? I wasn't ever able to recreate it.

**Comment by psyqotic** [comment]
@nbaggett I haven't attempted to play that scene since Weston started optimizing it. We can see what happens in the build this week.

**Comment by nbaggett** [comment]
I'm gonna close this for now since it didn't seem to happen in the build. I can re-open it if this pops up again.
