### ISSUE TITLE
Lore book text blocked by thumbs

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/TheOccultBugTracker#454]
### Feedback

Maybe move the thumbs back and/or give the book a bigger margin so no words are covered

### (Optional) Screen Recording or Screenshot

![20231130130454_1](https://github.com/westonleavitt/TheOccultBugTracker/assets/105509370/d4a1db89-1a48-47e9-8d96-e189e2f5326d)

**Comment by lukewoodruff** [comment]
Fixed IK
