### ISSUE TITLE
Monument spawner waypoints not randomizing

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#48]
This video is mostly observing two spawned enemies, but it's the case with other spawned enemies as well. They seem to pick the first waypoint, or just pick one randomly first, then continuously patrol a small area near that point instead of going to each waypoint randomly. The GiantRat AI seems to perform better than Goblin AI and Darkness Warlord AI, but my eyes kinda glazed over after watching awhile. Teehee

https://streamable.com/fso3v0

**Comment by nbaggett** [comment]
@psyqotic can you do one thing for me? On the goblin in play mode navigate to the Debug panal on their AIStateController and enable the ShowDebug option? This should give a line renderer viz of their desired path.
![image](https://user-images.githubusercontent.com/43483627/211867352-083ed323-b412-4313-8367-c7bd61e84854.png)

I just tested it on an AI in another scene and it is navigating to their patrol points correctly, but it might be the case that they don't have enough time to get there or that the point is unachievable.

**Comment by psyqotic** [comment]
Yeah, here's one with debug turned on. Looks like they start to go to a new waypoint then go "nope" and turn back.

https://streamable.com/skqmgo

**Comment by nbaggett** [comment]
Fixed in latest push
