### ISSUE TITLE
Distance Blur

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/TheOccultBugTracker#51]
The distance blur of the camera is way too strong. It's super obvious when in a relatively open space and feels much worse when walking/running around. But I don't know that it is very clear on video.

https://streamable.com/73mzus

**Comment by westonleavitt** [comment]
this is dependent on what volume you have running in the scene. Consider changing it to one of the static gaia volumes depending on what type of lighting you need to test with:

![image](https://user-images.githubusercontent.com/99469587/212158261-c3f6bd49-bc7b-44b2-bcbc-323dcdc93646.png)
