### ISSUE TITLE
When opening the menu it overrides? the post process volume?

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/TheOccultBugTracker#52]
https://streamable.com/wgig02

When opening the alt menu, the underwater post process volume is turned off or some other lighting is activated, and it becomes very bright. It doesn't seem to happen when you first load into the play mode and the alt menu is open by default but once you close it and reopen it, everything gets bright. It does go back to normal when you close the menu.

**Comment by nbaggett** [comment]
changed assignee to match feature owner
