### ISSUE TITLE
Teleport Spawning

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/TheOccultBugTracker#56]
When you load into a scene you get launched off into some direction. It does allow you to respawn normally. It's just when you first load into play mode. I've tried it on multiple scenes and it's the same in all of them. Except one time for reasons I don't understand, it did it as expected the first load in, then the second and third loads into the hamlet scene it didn't do it. But I can't reproduce the no warp thing again. Regardless of which scene I try it on. 
I've been working all day constantly spawning in to test things, so I've loaded in at least 50 times in the underwater scene and not once did I ever spawn normally. It always threw me away. I've tried disabling literally everything in the scene except the spawn point and it still happened. I moved the spawn point waaaaay up into the sky where I know I haven't ever placed anything, tried different spawn points. It still happens every time. It does seem to choose the same place to push you each time you load in though. So I'm guessing the times it worked in the hamlet scene were that I just got lucky in the spawn push and it chose the ground. I went back to see if I could reproduce it and now it spawns me at more or less the right place but under the map so I just fall into the abyss. 

Underwater Spawn Attempt and respawn command: https://streamable.com/by4v5w

Hamlet Spawn Attempt: https://streamable.com/4t62tx

Hamlet Successful Spawn: https://streamable.com/a5y30y

**Comment by tykennington** [comment]
I made your position persist when you quit and and start again. But I just realized that's just one position saved across scenes. What I suspect is happening is that you go somewhere in one scene and quit, saving that position. And then you switch scenes, so that position is loaded into the other scene, where it's somewhere weird

**Comment by mckayrules** [comment]
That could be. The first spawn I did this morning was fine (I think). But every one since then has been crazy.

**Comment by tykennington** [comment]
If you delete the file at C:\Users\[username]\AppData\LocalLow\Wunder Entertainment\Wunderhaven (Early Access)\playerData.json, it'll go back to normal on the next test. Right now though it'll generate the file again next time you quit play mode. I'm trying to decide what to do about that, maybe I'll add a checkbox or something so you can disable it for testing

**Comment by mckayrules** [comment]
Maybe you could make a spawn point that takes priority over the saved data so we could just place that when editing and it would be removed for builds etc.

**Comment by tykennington** [comment]
You can now turn this persistence feature on and off in testing, with the console "UsePersistence" command. I made it off by default, so it should go back to normal unless you want it to not
