### ISSUE TITLE
cannot upgrade wood doorframe

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#57]
### What happened?

![image](https://user-images.githubusercontent.com/99469587/213843107-36e9c27a-aa65-46cb-af60-e3049940439f.png)
guessing this has to do with when we adjusted the colliders

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

build a wooden door frame, you never get the upgrade prompt material color

### Screen Recording or Screenshot

![image](https://user-images.githubusercontent.com/99469587/213843115-421f6d78-b816-4e80-90d8-75fdca6a05b3.png)

**Comment by nbaggett** [comment]
fixed in latest push, also fixed the build audio not working for log and stone
