### ISSUE TITLE
Verify that AI gets placed on a nav mesh

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#68]
### What happened?

Verify that AI gets placed on a nav mesh

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Verify that AI gets placed on a nav mesh

### Screen Recording or Screenshot

Verify that AI gets placed on a nav mesh

**Comment by nbaggett** [comment]
Hoping this code works, I've added this to the open world spawn manager which should be the only script spawning in AI. 

```
// Make absolutely sure the AI is on a nav mesh, if not destroy it immediately and continue
if (!spawnedAI.GetComponent<NavMeshAgent>().isOnNavMesh)
{
    Destroy(spawnedAI);
    continue;
}
```
