### ISSUE TITLE
Building - Stairs conflict with walls etc.

### ISSUE THREAD

**Issue by camthem4n** [westonleavitt/TheOccultBugTracker#71]
### Contact Details

MrDOOD

### What happened?

Tried building walls around my placed stairs but couldnt

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

foundation, floor, stairs, walls 

### Screen Recording or Screenshot

https://streamable.com/d3auwc

**Comment by nbaggett** [comment]
fixed in latest push
