### ISSUE TITLE
lost souls should despawn when empty

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#78]
### What happened?

![image](https://user-images.githubusercontent.com/99469587/214987178-93d26ac3-e09b-443c-bba8-dcc0d95e4464.png)

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

despawn that baby when its empty

### Screen Recording or Screenshot

despawn that baby when its empty

**Comment by tykennington** [comment]
Fixed by commit fbb9aac
