### ISSUE TITLE
Ladder script interact text prompt and rappel function

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#81]
### Feedback

Could you add an interact custom text field on the ladder script? So for whatever it is being used for when you're in range of the trigger collider an interact prompt pops up that we can have say "Climb Ladder", "Use Zipline", "Rappel", etc etc. That'd be sweet!

Also, if you could take a look at the RappelLong prefab I pushed, I've tried to make it automatic so that when you interact with it you just slowly slide down the rope, but the player just stays at the top without moving. I tried copying the setup you have on the ziplines, but keep failing somehow. haha. Right now it's set up so that you can interact with it only at the top and climb up or down, but if you're at the bottom you can't interact with it (the trigger collider is only at the top). Anyway, long story short, I want the player to automatically slide down the rope and NOT be able to climb up it.

Thanks!

### (Optional) Screen Recording or Screenshot

![image](https://user-images.githubusercontent.com/99694322/215838113-85302afb-d5bf-496d-92f0-0fc9416a6b17.png)

**Comment by tykennington** [comment]
I don't have it working with the prompts yet, but I did fix the RappelLong prefab.

The issues I spotted:

1. The Local Path Direction was backwards. In needed to have a negative Y to move downwards.
2. The speed curve is speed over distance. So it cannot start at zero, or it'll never get going. I changed the start of the curve to 0.1.
3. The top and bottom point needed to be reversed. This is kind of weird and makes no sense, but it started out as a ladder, where you typically go up, so an "automatic ladder" goes from bottom to top. I should probably rename them as bottom -> start and top -> end
