### ISSUE TITLE
Add ability to interact with other interactables without falling off ladder

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#82]
### Feedback

This is the first time this has come up, but I foresee other circumstances where we could use this functionality. If you could make it so it's possible to interact with gates/doors/hatches/etc without falling off the ladder that'd be sweet! 

### (Optional) Screen Recording or Screenshot

https://streamable.com/x3o5oa

**Comment by tykennington** [comment]
fixed in commit 359d2c5
