### ISSUE TITLE
Any time an item gets consume that slot then becomes a black hole of never ending loss

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#85]
### What happened?

start the game and spawn in an apple. right click to eat the apple and then drag a new item into the slot the apple was in. it will disappear. This can occur for items as well that get consumed, like wood when building

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

start the game and spawn in an apple. right click to eat the apple and then drag a new item into the slot the apple was in. it will disappear. This can occur for items as well that get consumed, like wood when building

**Comment by tykennington** [comment]
Fixed with commit 60bb97e
