### ISSUE TITLE
Quest issues when interacting with NPC

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#88]
### What happened?

1) Quests not always showing as an option despite being assigned
2) When a quest is an option it's always the same one - *update - I just tested again and got a different quest for the first time, so it may have just been a 20% chance roll of the dice that I got the same quest repeatedly and may not actually be an issue after all
3) After interacting with NPC the name above the options doesn't match 

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Talk to blacksmith NPC in scene 0-WH-Test (Jake)

### Screen Recording or Screenshot

![image](https://user-images.githubusercontent.com/99694322/226678030-dcd8b8e3-ef25-47bd-981b-c829521ad082.png)
![image](https://user-images.githubusercontent.com/99694322/226678334-5ab1f254-c8fe-4f98-bedb-d1a0c61bd430.png)

**Comment by tykennington** [comment]
Fixed in commit 88b6a02
