### ISSUE TITLE
Quest tracker text overlap

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#89]
### What happened?

A combination of the quest title being long and multiple requirements for completion causes the quest tracker text to overlap

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

One example is to start the Craftsman Landmark quest

### Screen Recording or Screenshot

![image](https://user-images.githubusercontent.com/99694322/228732726-d66b7a43-075b-463d-aebc-d4cdd8d90e31.png)

**Comment by tykennington** [comment]
UI still needs more work, but this specific problem should be fixed now (commit ee9a37e)
