### ISSUE TITLE
Items carry over when you respawn

### ISSUE THREAD

**Issue by nbaggett** [westonleavitt/TheOccultBugTracker#93]
### What happened?

Items carry over when you respawn

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

1. Die with something equipped
2. Respawn
3. Its still equipped

**Comment by tykennington** [comment]
Fixed. It was syncing inventory back to the server from the client, which was overwriting the changes from loot dropping. I removed that, and now you are losing the half of your inventory, weapons, and armor that are dropped as loot
