### ISSUE TITLE
Well water consumable not working

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#98]
### What happened?

When you interact with the well, the prompt changes as if you've received the water, but nothing enters your inventory or consumable slots.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Interact with well

### Screen Recording or Screenshot

![MicrosoftTeams-image (2)](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/f54b9bfe-41cc-4f95-806a-50f176d61098)
![MicrosoftTeams-image (3)](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/e858ffa8-3e3e-4d43-9c0b-9ea5f6a9b835)

**Comment by tykennington** [comment]
Fixed in commit d37c13f
